#ifndef SHAREINFO_E_COLLISION_OBJECT_TYPE_H_
#define SHAREINFO_E_COLLISION_OBJECT_TYPE_H_

namespace ShareInfo
{
enum E_COLLISION_OBJECT_TYPE
{
	COLLISION_OBJECT_EMPTY		= -1,
	COLLISION_OBJECT_STAGE		= 0,
	COLLISION_OBJECT_ENMEY,
	COLLISION_OBJECT_MOVE_FLOOR,

	MAX_COLLISION_OBJECT_TYPE
};

} // namespace ShareInfo

#endif // #ifndef SHAREINFO_E_COLLISION_OBJECT_TYPE_H_